skip_tags: true
image: Visual Studio 2017
build:
  verbosity: normal
environment:
  NuGetOrgApiKey: 
    secure: u8JpW5kkti8pMi+ra2QcXTJPhkHCA8pkKSiiZOJbcS/vFVHNvF3W8qw1Fy2If6a7
  PUBLIC_NUGET_FEED_NAME: nuget.org
  PUBLIC_NUGET_FEED_SOURCE: https://www.nuget.org/
  BENCHMARKS: on
build_script:
- cmd: dotnet restore ./src/DotNetGlob.sln --disable-parallel
- cmd: dotnet build ./src/DotNetGlob.sln --disable-parallel
- cmd: dotnet pack ./src/DotNetGlob.sln --output ../../artifacts/
test: off
artifacts:
- path: ./artifacts/*